### ISSUE TITLE
안녕하세요!!

### ISSUE THREAD

**Issue by ehdrylang** [basquiat78/WebFlux-R2DBC#1]
KSUG 게시글 통해서 온 사람입니다!
webflux + r2dbc에 관한 좋은 글 잘봤습니다!!
흔하지 않은 내용인데 미리 경험해보시고 가이드로 참고할 수 있게 해주셔서 감사합니다.
감사의 인사와 더불어 높은 완성도에 도움이 될까싶어 조심스럽게 오타를... 알려드리려고 이슈 남깁니다.
[README.md]
duprecated -> deprecated

**Comment by basquiat78** [comment]
아 ㅋㅋㅋㅋㅋ 감사합니다. duplicated라는 변수명을 요즘 들어 자주 쓰게 되는데 습관처럼 썼나봅니다.

**Comment by basquiat78** [comment]
> KSUG 게시글 통해서 온 사람입니다!
> webflux + r2dbc에 관한 좋은 글 잘봤습니다!!
> 흔하지 않은 내용인데 미리 경험해보시고 가이드로 참고할 수 있게 해주셔서 감사합니다.
> 감사의 인사와 더불어 높은 완성도에 도움이 될까싶어 조심스럽게 오타를... 알려드리려고 이슈 남깁니다.
> [README.md]
> duprecated -> deprecated

아 ㅋㅋㅋㅋㅋ 감사합니다. duplicated라는 변수명을 요즘 들어 자주 쓰게 되는데 습관처럼 썼나봅니다.
